apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-apnk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-apnk@sha256:111ab53d14141d51cb39e52ea7d7a0539a9c18cab55c2959dbb3909f433e34dd
        name: my-nodejs
        resources: {}
status: {}
